#spring:
#  jackson:
#    date-format: yyyy年MM月dd日 HH时mm分ss秒
#    time-zone: Asia/Shanghai

spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  mail:
    host: smtp.gmail.com    # 邮件服务器主机地址
    port: 587                 # SMTP 端口
    username: ${GMAIL_USERNAME}  # 从环境变量中读取
    password: ${GMAIL_PASSWORD}  # 从环境变量中读取
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: on
